matrix:
  include:
    - os: osx
      osx_image: xcode8
      language: generic
      sudo: required
      env: PYTHON_VERSION="2"
    - os: osx
      language: generic
      sudo: required
      env: PYTHON_VERSION="3"
    - os: linux
      sudo: required
      dist: xenial
      language: python
      python: "2.7_with_system_site_packages"
      env: PACKAGES="xvfb gir1.2-gtk-3.0 gir1.2-webkit2-4.0 python-gi python-gi-cairo pep8 pyflakes python-pytest python-six" PYTHON="python"
    - os: linux
      sudo: required
      dist: xenial
      language: python
      env: PACKAGES="xvfb gir1.2-gtk-3.0 gir1.2-webkit2-4.0 python3-gi python3-gi-cairo python3-pep8 pyflakes python3-pytest python3-six" PYTHON="python3"
      python: "3.5_with_system_site_packages"
    - os: linux
      sudo: required
      dist: trusty
      language: python
      python: "3.4_with_system_site_packages"
      env: 
         - PACKAGES="xvfb python3-pyqt5 python3-pyqt5.qtwebkit libqt5webkit5-dev python3-pep8 pyflakes python3-pytest python3-six" PYTHON="python3"
         - PYWEBVIEW_GUI=qt
    - os: linux
      sudo: required
      dist: xenial
      language: python
      python: "3.5_with_system_site_packages"
      env: 
         - PACKAGES="xvfb python3-pyqt5 python3-pyqt5.qtwebkit libqt5webkit5-dev python3-pep8 pyflakes python3-pytest python3-six" PYTHON="python3"
         - PYWEBVIEW_GUI=qt
    - os: linux
      sudo: required
      dist: xenial
      language: python
      python: "2.7_with_system_site_packages"
      env: 
          - PACKAGES="xvfb python-qt4 libqtwebkit-dev pep8 pyflakes python-pytest" PYTHON="python"
          - PYWEBVIEW_GUI=qt

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$PYTHON_VERSION" == "3" ]]; then pip3 install pyobjc pytest six; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$PYTHON_VERSION" == "2" ]]; then sudo pip2 install pyobjc pytest six; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y $(echo $PACKAGES); fi
    
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e "Xvfb :0 -screen 0 1024x768x24 &" ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ "$PYTHON_VERSION" == "3" ]]; then python3 -m pytest tests; else python2 -m pytest tests; fi; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python -m pytest tests -s; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then killall Xvfb; fi

notifications:
  email: false
